### ISSUE TITLE
date_string validator

### ISSUE THREAD

**Issue by ozziexsh** [ozziexsh/validate#13]
this should validate that a date string is a specified format

something like

```elixir
date_string: "y-m-d"
```

which expects a date like 2020-04-28

what should the format string be based on? native datetime formats or timex? are they different?

**Comment by alanbosco003** [comment]
can you please assign this to me?

**Comment by ozziexsh** [comment]
added in v1.3.0

https://github.com/ozziexsh/validate/releases/tag/v1.3.0
